language: python
sudo: false
cache: pip
python:
  - "2.7"
  - "3.5"
before_install:
  - pip install --upgrade pip
  - pip install wheel
  - pip install numpy scipy scikit-learn matplotlib
script: nosetests
